# This is a basic workflow to help you get started with Actions

name: CI Cyoress

# Controls when the workflow will run
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: action/checkout@v2.4.2
      - name: Install depedencies
        run: npm install
      - name: Cypress.io
        uses: cypress.io/github-action@v2.9.7
        with:
          working-directory: ./app
